music_app/rtm_music_app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#new"
  resources :users, only: [:new, :show, :create]

  resources :bands

  resource :session, only: [:new, :create, :destroy]

  


end

music_app/rtm_music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

music_app/rtm_music_app/app/models/band.rb
class Band < ApplicationRecord

  validates :name, presence: true, uniqueness: true

end

music_app/rtm_music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true

  validates :password, length: {minimum: 6}, allow_nil: true

  before_validation :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  attr_reader :password

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    password_object = BCrypt::Password.new(self.password_digest)
    password_object.is_password?(password)
  end

  def generate_unique_session_token
    SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = generate_unique_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= generate_unique_session_token
  end

end

music_app/rtm_music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  skip_before_action :verify_authenticity_token

  helper_method :current_user, :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out
    redirect_to users_url if logged_in?
  end

end

music_app/rtm_music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  # before_action
end

music_app/rtm_music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ['Invalid email or password']
      render :new
    end
  end

  def destroy
    logout!
    flash[:messages] = ["Successfully logged out."]
    redirect_to new_session_url
  end

  private
  def credentials
    [params[:user][:email], params[:user][:password]]
  end

end

music_app/rtm_music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    render :new
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/rtm_music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/rtm_music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Melodionia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>
  <header>
  <h2>Melodionia</h2>
  <nav>
    <% if logged_in? %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Logout">
      </form>
    <% else %>
      <a href="<%= new_user_url %>">Sign Up</a>
      <a href="<%= new_session_url %>">Login</a>
    <% end %>
  </nav>
  </header>
  <body>

    <%= yield %>
  </body>
</html>

music_app/rtm_music_app/app/views/users/_form.html.erb
<form action="<%= users_url %>" method="post">
    <label for="email">Email: </label>
    <input type="text" name="user[email]" id="email">
    <br>
    <label for="password">Password: </label>
    <input type="password" name="user[password]" id="password">
    <br>
    <input type="submit" value="Sign Up">
</form>

music_app/rtm_music_app/app/views/users/new.html.erb
<h3>Sign Up</h3>

<%= render 'form' %>

music_app/rtm_music_app/app/views/users/show.html.erb
<h3>Welcome <%= @user.email %></h3>

<ul>
    <li><%= @user.email %> is your email</li>
</ul>